### ISSUE TITLE
ContextInitializer.autoConfig() doesn't close resource that could be leak

### ISSUE THREAD

**Issue by FilenkovMaxim** [tony19/logback-android#191]
`implementation 'com.github.tony19:logback-android:1.3.0-2'`

Run
```
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
          .detectAll()
          .penaltyLog()
          .build());
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
          .detectAll()
          .penaltyLog()
          .build());

ContextInitializer ci = new ContextInitializer(lc);
ci.autoConfig();
```
got the error
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.util.zip.ZipFile.<init>(ZipFile.java:185)
        at java.util.jar.JarFile.<init>(JarFile.java:199)
        at libcore.net.url.JarURLConnectionImpl.openJarFile(JarURLConnectionImpl.java:136)
        at libcore.net.url.JarURLConnectionImpl.findJarFile(JarURLConnectionImpl.java:125)
        at libcore.net.url.JarURLConnectionImpl.connect(JarURLConnectionImpl.java:82)
        at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:215)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source)
```

**Comment by tony19** [comment]
I can't reproduce the problem. Can you provide a link to a GitHub repo that exhibits this?

Note that you shouldn't be calling `ContextInitializer.autoConfig()` because it's already automatically called (hence its name).

**Comment by FilenkovMaxim** [comment]
Did you set StrictMode?
I call it because I clean log directory after I sent logs to my server.

**Comment by tony19** [comment]
Yes, I enabled StrictMode.

**Comment by FilenkovMaxim** [comment]
Ok, I'll try to reproduce this in a blank example and will upload it to github.

**Comment by tony19** [comment]
The [`GenericConfigurator.doConfigure()`](https://github.com/tony19/logback-android/blob/37d0f40/logback-android/src/main/java/ch/qos/logback/core/joran/GenericConfigurator.java#L46) methods should be closing the input streams in a `finally` block, which resolves the issue. In addition, the [`lc.reset()` in `resetLogs()`](https://github.com/FilenkovMaxim/LogbackExample/blob/33c6558/app/src/main/java/com/example/maxf/logbackexample/MainActivity.java#L36) should be `lc.stop()` in your case in order to properly close all logback resources (such as `AsyncAppender` worker threads).

**Comment by FilenkovMaxim** [comment]
@tony19 thank you. I'll fix this.

**Comment by FilenkovMaxim** [comment]
@tony19 I've checked. Without ci.autoConfig(); logback doesn't create new log file until app restart.
If I should not use ci.autoConfig(); how I can start writing logs to new file?

**Comment by tony19** [comment]
Fixed in [v_1.3.0-3](https://github.com/tony19/logback-android/releases/tag/v_1.3.0-3)

**Comment by FilenkovMaxim** [comment]
Hello.
I tried 
`implementation 'com.github.tony19:logback-android:1.3.0-3'`
and
```
LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();
    lc.reset();
    lc.stop();
```
but it still doesn't create new log file until app restart.

**Comment by tony19** [comment]
@FilenkovMaxim That's unrelated to this issue, which was about a resource leak. With your original code (including `ci.autoConfig()`), you'll no longer observe the resource-leak exceptions.

Btw, you should **replace** `lc.reset()` with `lc.stop()` (don't do both).
